config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get '/:year/:month/blogs', to: 'blogs#month'
  get 'angular', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  get 'new-skill', to: 'pages#new_skill'
  post 'skills', to: 'pages#create_skill'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  mount ActionCable.server => '/cable' 
  #going to open upa web socket connection that we can use in order to connect in and send data receive data
  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, :body, :topic_id, presence: true
  belongs_to :topic
  has_many :comments, dependent: :destroy

  def self.special_blogs
    self.all
  end

  def self.featured_blogs
    limit(2)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_topics_sidebar, except: [:destory, :update, :create, :toggle_status]#reason is we don't want to call this inside of action items that are not GET request
  layout "blog"
  access all: [:show, :index, :paginate], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all
  # GET /blogs
  # GET /blogs.json

  def index
    if logged_in?(:site_admin)
      @blogs = Blog.page(params[:page]).per(5).order(created_at: :desc)
      #@blogs = Blog.all
    else 
      @blogs = Blog.published.page(params[:page]).per(5).order(created_at: :desc)
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        # format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        # format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        # format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        # format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published! 
      @blog.update(created_at: Time.now)
    elsif @blog.published?
      @blog.draft! 
    end
    redirect_to @blog, notice: "Post status has been changed."
  end
  def month
    @blogs = Blog.page(params[:page]).per(5).where('extract(year  from created_at) = ?', params[:year]).where('extract(month  from created_at) = ?', params[:month]).order("created_at DESC")

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :status, :topic_id)
    end
    def set_topics_sidebar
      @sidebar_topics = Topic.with_blogs.limit(5)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    # image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
    # include MD5 gem, should be part of standard ruby install
    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase
    
    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)
    
    # compile URL which can be used in <img src="RIGHT_HERE"...
    image_tag "https://www.gravatar.com/avatar/#{hash}", width: 60
  end

  # Create a custom renderer that sets a custom class for block-quotes.
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end
  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    options = {
      fenced_code_blocks: true,
      np_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,

    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
  def blog_parser blog
    @blog_url = PointOutUrl::Renderer.text_parser blog
  end

end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h4 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h4>
  <p class="blog-post-meta">Published at <%= blog.created_at.strftime("%Y-%m-%d") %> ( <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago )</p>
  
  <% if logged_in?(:site_admin) %>
  <nav class="breadcrumb">
    <%= link_to blog.status.capitalize, toggle_status_blog_path(blog), class: "breadcrumb-item" %> 
    <%= link_to 'Edit', edit_blog_path(blog), class: "breadcrumb-item" %> 
    <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "breadcrumb-item" %>
  </nav>
  <% end %>

  <p>
    <%= markdown(blog_parser blog.body) %>
  </p>
</div>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <h3><%= pluralize(blog.errors.count, "errors") %> prohibited this blog from being saved:</h3>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label "Title"%>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control", rows: 15 %>
  </div>
  <div class="form-group">
    <%= f.label "Topic"%>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                selected: blog.topic_id,
                                include_blank: true

                              },
                              class: "form-control"
                              )
    %>

  </div>
  <div class="form-group">
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, 'Draft' %>
    <%= f.radio_button :status, 'published' %>
    <%= f.label :status, 'Published' %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h2>Editing Blog</h2>
  
  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= paginate @blogs %>
  <%= render @blogs %>
  <%= paginate @blogs %>

</div><!-- /.blog-main -->

app/views/blogs/month.html.erb
 <% if @blogs.count > 0 %>

  <div class="col-sm-8 blog-main">
    <%= paginate @blogs %>
    <%= render @blogs %>
    <%= paginate @blogs %>

  </div><!-- /.blog-main -->
<% else %>
  <div class="col-sm-8 blog-main">
    <h4> This month no blog posts!</h4>
    <p>
      <%= link_to 'Back to Blogs', blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>

<% end %>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <div class="blog-show">
    <h2>
      <%= @blog.title %>
    </h2>
    <h5 class="text-muted">( Topic:  <%= link_to @blog.topic.title, topic_path(@blog.topic) %>)</h5>
    <nav class="breadcrumb">
      <% if logged_in?(:site_admin) %>
      <%= link_to @blog.status.capitalize, toggle_status_blog_path(@blog), class: "breadcrumb-item" %> 
      <%= link_to fa_icon("edit"), edit_blog_path(@blog), class: "breadcrumb-item" %>
      <%= link_to fa_icon("trash"), @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "breadcrumb-item" %>
      <% end %>
      <%= link_to 'Back', blogs_path, class: "breadcrumb-item" %>
    </nav>
    <p>
      <%= markdown(blog_parser @blog.body) %>
    </p>
  </div>

  <!-- Start of comment form -->
  <%= render 'comments/comment_form' %>
  <!-- end form -->
  <!-- Start of comments -->
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
  <!-- end form -->



</div>