config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get '/:year/:month/blogs', to: 'blogs#month'
  get 'angular', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  get 'new-skill', to: 'pages#new_skill'
  post 'skills', to: 'pages#create_skill'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  mount ActionCable.server => '/cable' 
  #going to open upa web socket connection that we can use in order to connect in and send data receive data
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                allow_destroy: true,
                                reject_if: lambda { |banana| banana['name'].blank? }

  # include Placeholder
  validates :title, :subtitle, :body, :thumb_image, :main_image, presence: true

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

    #custom scope
  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end
  scope :My_great_project_subtitle, -> { where(subtitle: 'My great project') }

  # after_initialize :set_default
  # def set_default
  #   #use concerns
  #   self.main_image ||= Placeholder.image_generator(height: "600", width:"400")
  #   self.thumb_image ||= Placeholder.image_generator(height: "350", width:"200")

  #   #self.main_image ||= "http://via.placeholder.com/600x400"
  #   #self.thumb_image ||= "http://via.placeholder.com/350x200"
  # end
  # :main_image, :thumb_image,
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular, :sort], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  def index
    # @portfolio_items = Portfolio.all
    # @portfolio_items = Portfolio.order("position ASC")
    @portfolio_items = Portfolio.by_position
  end
  def sort 
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end
  def angular
    @angular_portfolio_items = Portfolio.angular
  end
  def new
    @portfolio_item = Portfolio.new

    #word build here is instantiate three versions/type of this portfolio item with technologies
    3.times { @portfolio_item.technologies.build }

  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
        # format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        # format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit 
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {
          redirect_to portfolios_path, notice: "Update successfully"
        }
      else
        format.html { render :edit }
      end
    end 
  end

  def show 
    
  end

  def destroy
    #perform the lookup

    #destroy the record
    @portfolio_item.destroy
    #redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end
end

private

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,  
                                        :main_image,
                                        :thumb_image,                                      
                                        technologies_attributes: [:id,:name, :_destroy]
                                        )
    end
    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  # def image_generator(height:, width:)
  #   "http://via.placeholder.com/#{height}x#{width}"
  # end
  # def portfolio_img img, type
  #   if img
  #     img
  #   elsif type == "thumb"
  #     image_generator(height: '350', width: "200")
  #   elsif type == "main"
  #     image_generator(height: "600", width: "400")
  #   end
  # end
  def project_parser project
    @project_url = PointOutUrl::Renderer.text_parser project
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |item|%>
  <% if @portfolio_item.errors.any? %>
    <h3><%= pluralize(@portfolio_item.errors.count, "errors") %> prohibited this portfolio from being saved:</h3>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= item.label :title, class: "form-label" %>
    <%= item.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= item.label :subtitle, class: "form-label" %>
    <%= item.text_field :subtitle, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= item.label :body, class: "form-label" %>
    <%= item.text_area :body, class: "form-control", rows:"8" %>
  </div>
  <div class="form-group">
    <label class="btn btn-primary">
      Upload a main image file <%= item.file_field :main_image, style: 'display:none;' %>
    </label>
  </div>
  <div class="form-group">
    <label class="btn btn-primary">
      Upload a thumb image file <%= item.file_field :thumb_image, style: 'display:none;', class:"thumb-image" %>
    </label>
  </div>
  <h3>Technologies Used: </h3>
  <div>
    <%= item.fields_for :technologies do |technology_form|%>
      <%= render 'technology_fields', f: technology_form %>
    <% end %>
    <div>
      <%= link_to_add_association 'Add Technology', item, :technologies %>
    </div>
  </div>
  <div class="form-group">
    <%= item.submit "Submit", class:"btn btn-primary btn-block" %>
  </div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_item.thumb_image.to_s, class: "thumb-image", width: "100%" %>
    <h1 class="card-text">
      <span><%= link_to portfolio_item.title, show_portfolio_path(portfolio_item) %></span> 
    </h1>
    <h2 class="card-text">Technologies:</h2>
    <div class="card-text row"><% portfolio_item.technologies.each do |technology_item| %>     
      <h3 class="card-text ml-3">*<%= technology_item.name %>   </h3>      
    <% end %></div>

    <p><%= link_to "Detail", show_portfolio_path(portfolio_item), class:"btn btn-secondary mt-2" %></p>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<div class="container"> 
  <h1>Portfolio</h1>
  <%= link_to "Create new portfolio", new_portfolio_url if logged_in?(:site_admin) %>
  <% @angular_portfolio_items.each do |item| %>
    <h3><%= link_to item.title, show_portfolio_path(item.id) %></h3>
    <h4><%= item.subtitle %></h4>
    <p><%= item.body %></p>
    <%= image_tag item.thumb_image if !item.thumb_image.nil? %>
    <%= link_to "Edit portfolio", edit_portfolio_path(item.id) %>
    <%# method: :delete  is important because there has other method use the same path%>
    <%= link_to 'Destroy', portfolio_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this portfolio</h1>
  <%= render 'form', item: @item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">

      <%= render partial: 'portfolio_item', collection:  @portfolio_items %>
    </div>
  </div>
</div>
    

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>New Portfolio</h1>
  <%= render 'form', item: @item %>

</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <%= image_tag @portfolio_item.main_image.to_s, width: "100%", class:"main-image" %>
  <h6 class="mt-1"><a href="<%= @portfolio_item.subtitle %>"> Go to project live site</a></h6>

  <h2><%= @portfolio_item.title %>
  </h2>

  <p>
    <%= project_parser @portfolio_item.body %>
  </p>
  <h2>Technologies include:</h2>

  <div class="row"><% @portfolio_item.technologies.each do |technology_item| %>     
    <h6 class="ml-3">*<%= technology_item.name %>   </h6>      
  <% end %></div>
<% if logged_in?(:site_admin) %>
  <div class="col-md-12">
    <%= link_to 'Edit', edit_portfolio_path(@portfolio_item.id), class: "btn btn-warning btn-block mt-2" %>
  </div>
<% end %>


</div>



<hr>
<%= source_helper('portfolio show') %>