config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get '/:year/:month/blogs', to: 'blogs#month'
  get 'angular', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  get 'new-skill', to: 'pages#new_skill'
  post 'skills', to: 'pages#create_skill'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  mount ActionCable.server => '/cable' 
  #going to open upa web socket connection that we can use in order to connect in and send data receive data
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<!-- Application Nav -->
<div class="masthead clearfix">
  <div class="inner">

    <h2 class="masthead-brand"> Xin Li</h2>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <%= render "shared/application_footer" %>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_header.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The Bootstrap Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <p><%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %></p>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<!-- Blog Nav -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark p-3 blog-nav">

  <div class="container">
    <%= image_tag 'favicons/girl.png' %>
    <%= link_to "Xin Li", root_path, class: "navbar-brand ml-2 mr-5" %>
    <button class="navbar-toggler" data-toggle="collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbarNav"> 
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="conllapse navbar-collapse" id="navbarNav">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper("nav-link") %>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>
      I will share my Life, Travel, Coding, Programming, Technology and so on informations in this blog and my other social media. Welcome to visit and leave comments.
  
    </p>

  </div>
  <div class="sidebar-module">
    <h4>Topics</h4>
    <ul class="list-unstyled social-link">
      <% @sidebar_topics.each do |topic| %>
        <li><%= link_to "#{topic.title}", topic_path(topic) %></li>
      <% end %>
    </ul>
    <h4><%= link_to 'See all topics', topics_path, class: "btn btn-primary" %></h4>
  </div>
  <div class="sidebar-module">
    <h4>Archives</h4>
    <ul class="list-unstyled">
      <li><a href="/2018/12/blogs">December 2018</a></li>
      <li><a href="/2018/11/blogs">November 2018</a></li>
      <li><a href="/2018/10/blogs">October 2018</a></li>
      <li><a href="/2018/09/blogs">September 2018</a></li>
      <li><a href="/2018/08/blogs">August 2018</a></li>
      <li><a href="/2018/07/blogs">July 2018</a></li>
      <li><a href="/2018/06/blogs">June 2018</a></li>
      <li><a href="/2018/05/blogs">May 2018</a></li>
      <li><a href="/2018/04/blogs">April 2018</a></li>
    </ul>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ul class="list-unstyled social-link">
      <li><%= fa_icon "github" %> <a href="https://github.com/sindyxin" class="ml-1"> GitHub</a></li>
      <li><%= fa_icon "linkedin" %> <a href="https://www.linkedin.com/in/xin-li-3b823a93/" class="ml-1"> Linkedin</a></li>
      <li><%= fa_icon "facebook" %> <a href="https://www.facebook.com/sindylixin" class="ml-2"> Facebook</a></li>
    </ul>
  </div>
</div><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div>
  <%= link_to 'Home', root_path %>
  <%= link_to 'About Me', about_me_path %>
  <%= link_to 'Contact', contact_path %>
  <%= link_to 'Portfolios', portfolios_path %>
  <%= link_to 'Blogs', blogs_path %>
  <%= link_to 'Tech News', tech_news_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">  
    <p class="float-right">
      <%= link_to 'View All Projects', portfolios_path %> /
      <a href="#">Back to top</a>    
    </p>  
    <p><%= render "shared/application_footer" %></p> 
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Projects</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <a href="https://drive.google.com/file/d/1Nc0VFfBc3eQfUvzOcu7AP_oSk2B9NePW/view?usp=sharing" class="btn btn-primary">See Resume</a>
      <%= link_to 'My Blog', blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<!-- Poerfolio Nav -->
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h2>About me</h2>
        <p>I am a full stack web developer who just graduated from the Coding Dojo in Burbank, CA knowledgeable in Python, MEAN, and Ruby. My past experiences in business and marketing industries have helped me develop problem-solving skills, multi-tasking abilities, and attention to detail. </p>
        <p>Now, I am seeking an opportunity where I can use my skills to make a new project or handle existing project.</p>
      </div>
      <div class="col-md-4 py-4">
        <h4>Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper "text-white", "li" %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">  
    <p><%= image_tag 'favicons/girl.png' %>
    <%= link_to 'Xin Li', root_path, class: "navbar-brand ml-2 mt-3 float-right" %></p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon float-right"></span>
    </button>
  </div>
</nav>